[project]
name = "basic-gpt"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = [
    "torch>=2.7.1,<3.0.0",
    "scikit-learn==1.6.1",
    "openai (>=1.107.0,<2.0.0)"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
